Docker Daemon check

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -40,6 +40,17 @@ determine_distro() {
 }
 
 determine_sudo() {
+    if [[ "$__distro" =~ "debian" || "$__distro" = "ubuntu" ]]; then
+        systemctl status docker >/dev/null
+        result=$?
+        if [ ! "${result}" -eq 0 ]; then
+            echo "The Docker daemon is not running. Please check Docker installation."
+            echo "\"sudo systemctl status docker\" and \"sudo journalctl -fu docker\" will be helpful."
+            echo "Aborting."
+            exit 1
+        fi
+    fi
+
     __maybe_sudo=""
     if ! docker images >/dev/null 2>&1; then
         echo "Will use sudo to access Docker"
@@ -65,7 +76,7 @@ determine_compose() {
     if [ -n "${ETHDSECUNDO-}" ]  || [ ! "${command}" = "update" ]; then # Don't run this twice
       echo
       echo "You are using docker-compose ${__compose_version}, which is unsupported by Docker, Inc."
-      echo "${__project_name} will stop supporting it sometime fall 2023."
+      echo "${__project_name} will stop supporting it sometime early 2024."
       echo ""
       echo "It is recommended that you replace Compose V1 with Compose V2."
       while true; do
@@ -718,7 +729,7 @@ if [ "${__compose_upgraded}" -eq 1 ]; then
 elif [ "${__old_compose}" -eq 1 ]; then
   echo
   echo "You are using docker-compose ${__compose_version}, which is unsupported by Docker, Inc. since July 2023."
-  echo "${__project_name} will stop supporting it sometime fall 2023."
+  echo "${__project_name} will stop supporting it sometime early 2024."
   echo ""
   echo "A switch to docker-ce is recommended. It is *not* mandatory. This is unfortunately a manual step that"
   echo "${__project_name} cannot do for you."
