Updates around install and compose update

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -2,8 +2,12 @@
 #set -euo pipefail
 set -uo pipefail
 
+__project_name="optimism-docker"
+__app_name="Optimism node"
+__sample_service="op-geth"
 __docker_exe="docker"
-__compose_exe="docker-compose"
+__compose_exe="docker compose"
+__compose_upgraded=0
 
 dodocker() {
     $__docker_exe "$@"
@@ -38,7 +42,7 @@ determine_distro() {
 determine_sudo() {
     __maybe_sudo=""
     if ! docker images >/dev/null 2>&1; then
-        echo "Will use sudo to access docker"
+        echo "Will use sudo to access Docker"
         __maybe_sudo="sudo"
     fi
 }
@@ -55,34 +59,23 @@ determine_compose() {
     __compose_exe="docker compose"
     __old_compose=0
   else
-    __old_compose=1
-    __compose_version=$($__maybe_sudo docker-compose --version | sed -n -e "s/.*version [v]\?\([0-9.-]*\).*/\1/p")
-    __compose_version_major=$(echo "$__compose_version" | cut -f1 -d.)
-    __compose_version_minor=$(echo "$__compose_version" | cut -f2 -d.)
-    if ! [ "$__compose_version_major" -eq "$__compose_version_major" ] && [ "$__compose_version_minor" -eq "$__compose_version_minor" ] 2> /dev/null; then
-        echo "docker-compose version detection failed. Please report this output so it can be fixed."
-        $__maybe_sudo docker-compose --version
-    elif [ "$__compose_version_major" -eq 1 ] && [ "$__compose_version_minor" -lt 28 ]; then
-      echo "Error: Outdated docker-compose version detected ($__compose_version). Please upgrade to version 1.28.0 or later." >&2
-      if [[ "$__distro" = "ubuntu" ]]; then
-        __major_version=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'// | cut -d. -f1)
-        if [ "${__major_version}" -lt 22 ]; then
-          echo
-          while true; do
-            read -rp "Do you want to update docker-compose to v1.29.2? (yes/no) " yn
-            case $yn in
-              [Nn]* ) echo "Please be sure to update docker-compose yourself!"; exit 1;;
-              * ) upgrade_compose; break;;
-            esac
-          done
-        fi
-      else
-        echo >&2
-        echo "On Debian 11, using docker-ce instead of docker.io, with the compose plugin, will work." >&2
-        exit 1
-      fi
-    fi
     __compose_exe="docker-compose"
+    __old_compose=1
+    __compose_version=$($__maybe_sudo docker-compose --version | sed -n -E -e "s/.*version [v]?([0-9.-]*).*/\1/ip")
+    if [ -n "${ETHDSECUNDO-}" ]  || [ ! "${command}" = "update" ]; then # Don't run this twice
+      echo
+      echo "You are using docker-compose ${__compose_version}, which is unsupported by Docker, Inc."
+      echo "${__project_name} will stop supporting it sometime fall 2023."
+      echo ""
+      echo "It is recommended that you replace compose V1 with compose V2."
+      while true; do
+        read -rp "Do you want to update compose to V2? (yes/no) " yn
+        case $yn in
+          [Nn]* ) echo "Please be sure to update compose yourself!"; break;;
+           * ) upgrade_compose; break;;
+        esac
+      done
+    fi
   fi
 
   if [ -n "$__maybe_sudo" ]; then
@@ -91,26 +84,63 @@ determine_compose() {
 }
 
 upgrade_compose() {
-  if type -P docker-compose >/dev/null 2>&1; then
-    __compose_version=$($__maybe_sudo docker-compose --version | sed -n -e "s/.*version \([0-9.-]*\).*/\1/p")
-    __compose_version_major=$(echo "$__compose_version" | cut -f1 -d.)
-    __compose_version_minor=$(echo "$__compose_version" | cut -f2 -d.)
-    if [ "$__compose_version_major" -eq 1 ] && [ "$__compose_version_minor" -lt 28 ]; then
-      echo "Found docker-compose version $__compose_version_major.$__compose_version_minor, upgrading to 1.29.2"
-      ${__auto_sudo} apt-get install -y curl
-      ${__auto_sudo} curl -fsSL "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
-      ${__auto_sudo} chmod +x /usr/bin/docker-compose
+  if ! type -P docker-compose >/dev/null 2>&1; then
+    echo "Docker Compose has already been updated to V2"
+    return
+  fi
+  echo "Updating Docker Compose to V2"
+  if [[ "$__distro" = "ubuntu" ]]; then
+    ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get install -y ca-certificates curl gnupg lsb-release
+    __major_version=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'// | cut -d. -f1)
+    if [ "${__major_version}" -lt 20 ]; then
+      echo "This script cannot update Docker Compose on Ubuntu ${__major_version}. Consider upgrading to 22.04 or 20.04"
+      exit 0
     fi
-    __compose_version=$($__maybe_sudo docker-compose --version | sed -n -e "s/.*version \([0-9.-]*\).*/\1/p")
-    __compose_version_major=$(echo "$__compose_version" | cut -f1 -d.)
-    __compose_version_minor=$(echo "$__compose_version" | cut -f2 -d.)
-    if [ "$__compose_version_major" -eq 1 ] && [ "$__compose_version_minor" -lt 28 ]; then
-      echo "Updating docker-compose failed. It is still version $__compose_version_major.$__compose_version_minor."
-      echo "Please manually update docker-compose to version 1.29.2. These commands should do it:"
-      echo "sudo curl -fsSL \"https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/bin/docker-compose"
-      echo "sudo chmod +x /usr/bin/docker-compose"
-      exit 1
+    if dpkg-query -W -f='${Status}' docker.io 2>/dev/null | grep -q "ok installed"; then
+        ${__auto_sudo} apt-mark manual docker.io
+    elif dpkg-query -W -f='${Status}' docker-ce 2>/dev/null | grep -q "ok installed"; then
+        ${__auto_sudo} apt-mark manual docker-ce
     fi
+    ${__auto_sudo} apt-get remove -y docker-compose
+    echo "Removed docker-compose"
+    ${__auto_sudo} mkdir -p /etc/apt/keyrings
+    ${__auto_sudo} curl -fsSL https://download.docker.com/linux/ubuntu/gpg | ${__auto_sudo} gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+    ${__auto_sudo} echo \
+        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+        $(lsb_release -cs) stable" | ${__auto_sudo} tee /etc/apt/sources.list.d/docker.list > /dev/null
+    ${__auto_sudo} apt-get update
+    ${__auto_sudo} apt-get install -y docker-compose-plugin docker-buildx-plugin
+    echo "Installed docker-compose-plugin"
+    __old_compose=0
+    __compose_exe="docker compose"
+    __compose_upgraded=1
+  elif [[ "$__distro" =~ "debian" ]]; then
+    ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get -y install ca-certificates curl gnupg lsb-release
+    __major_version=$(lsb_release -r | cut -f2)
+    if [ "${__major_version}" -lt 10 ]; then
+        echo "This script cannot update Docker Compose on Debian ${__major_version}. Consider upgrading to 11 or 12."
+        exit 0
+    fi
+    if dpkg-query -W -f='${Status}' docker.io 2>/dev/null | grep -q "ok installed"; then
+        ${__auto_sudo} apt-mark manual docker.io
+    elif dpkg-query -W -f='${Status}' docker-ce 2>/dev/null | grep -q "ok installed"; then
+        ${__auto_sudo} apt-mark manual docker-ce
+    fi
+    ${__auto_sudo} apt-get remove -y docker-compose
+    echo "Removed docker-compose"
+    ${__auto_sudo} mkdir -p /etc/apt/keyrings
+    ${__auto_sudo} curl -fsSL https://download.docker.com/linux/debian/gpg | ${__auto_sudo} gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+    ${__auto_sudo} echo \
+        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
+        $(lsb_release -cs) stable" | ${__auto_sudo} tee /etc/apt/sources.list.d/docker.list > /dev/null
+    ${__auto_sudo} apt-get update
+    ${__auto_sudo} apt-get install -y docker-compose-plugin docker-buildx-plugin
+    echo "Installed docker-compose-plugin"
+    __old_compose=0
+    __compose_exe="docker compose"
+    __compose_upgraded=1
+  else
+    echo "This script does not know how to update Docker Compose on $__distro"
   fi
 }
 
@@ -127,13 +157,13 @@ handle_root() {
 check_for_snap() {
     if [[ "$__distro" = "ubuntu" && -n "$(which snap)" ]] && snap list 2>/dev/null | grep -qw 'docker'; then
         echo
-        echo "WARNING! Snap docker package detected. This WILL result in issues."
+        echo "WARNING! Snap Docker package detected. This WILL result in issues."
         echo "Removing the package will delete volumes and require a resync."
         echo
         echo "Doing so is still highly recommended however."
         echo
         echo "The exact steps depend a little on whether there already is"
-        echo "an apt version of docker installed as well, but in a nutshell"
+        echo "an apt version of Docker installed as well, but in a nutshell"
         echo '"./ethd stop" followed by "sudo snap remove --purge docker"'
         echo "and then a reboot, and as needed install docker.io or docker-ce with apt."
         echo
@@ -148,7 +178,7 @@ install() {
     check_for_snap
     set -e
     while true; do
-        read -rp "This will attempt to install docker and make your user part of the docker group. Do you wish to continue? (no/yes) " yn
+        read -rp "This will attempt to install Docker and make your user part of the docker group. Do you wish to continue? (no/yes) " yn
         case $yn in
             [Yy]* ) break;;
             * ) echo "Aborting, no changes made"; exit 0;;
@@ -157,17 +187,19 @@ install() {
     if [[ "$__distro" = "ubuntu" ]]; then
         __major_version=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'// | cut -d. -f1)
         if [ "${__major_version}" -lt 20 ]; then
-            echo "This script cannot install docker on Ubuntu ${__major_version}. Consider upgrading to 22.04 or 20.04"
+            echo "This script cannot install Docker on Ubuntu ${__major_version}. Consider upgrading to 22.04 or 20.04"
         fi
         if [ -z "$(which docker)" ]; then
-            ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get install -y ca-certificates curl gnupg lsb-release whiptail bc chrony
+            ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get install -y ca-certificates curl gnupg lsb-release \
+                chrony pkg-config
             ${__auto_sudo} mkdir -p /etc/apt/keyrings
             ${__auto_sudo} curl -fsSL https://download.docker.com/linux/ubuntu/gpg | ${__auto_sudo} gpg --dearmor -o /etc/apt/keyrings/docker.gpg
             ${__auto_sudo} echo \
                 "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                 $(lsb_release -cs) stable" | ${__auto_sudo} tee /etc/apt/sources.list.d/docker.list > /dev/null
             ${__auto_sudo} apt-get update
-            ${__auto_sudo} apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
+            ${__auto_sudo} apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin \
+                docker-buildx-plugin
             echo "Installed docker-ce and docker-compose-plugin"
         else
             echo "Docker is already installed"
@@ -183,10 +215,10 @@ install() {
     elif [[ "$__distro" =~ "debian" ]]; then
         if [ -z "$(which docker)" ]; then
             ${__auto_sudo} apt-get update
-            ${__auto_sudo} apt-get -y install ca-certificates curl gnupg lsb-release whiptail bc chrony
+            ${__auto_sudo} apt-get -y install ca-certificates curl gnupg lsb-release chrony pkg-config
             __major_version=$(lsb_release -r | cut -f2)
             if [ "${__major_version}" -lt 10 ]; then
-                echo "This script cannot install docker on Debian ${__major_version}. Consider upgrading to 11 or 12."
+                echo "This script cannot install Docker on Debian ${__major_version}. Consider upgrading to 11 or 12."
                 exit 0
             fi
             ${__auto_sudo} mkdir -p /etc/apt/keyrings
@@ -195,7 +227,8 @@ install() {
                 "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
                 $(lsb_release -cs) stable" | ${__auto_sudo} tee /etc/apt/sources.list.d/docker.list > /dev/null
             ${__auto_sudo} apt-get update
-            ${__auto_sudo} apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
+            ${__auto_sudo} apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin \
+                docker-buildx-plugin
             echo "Installed docker-ce and docker-compose-plugin"
         else
             echo "Docker is already installed"
@@ -209,7 +242,7 @@ install() {
             echo "Your user is already part of the docker group"
         fi
     else
-        echo "This script does not know how to install docker on $__distro"
+        echo "This script does not know how to install Docker on $__distro"
     fi
     set +e
     return 0
@@ -584,7 +617,7 @@ printhelp() {
     echo ""
     echo "subcommands:"
     echo "  install"
-    echo "     attempts to install docker and docker-compose for you"
+    echo "     attempts to install Docker and Docker Compose for you"
     echo "  update "
     echo "     updates all client versions and optimism-docker itself"
     echo "  up (or start)"
@@ -599,7 +632,7 @@ printhelp() {
     echo "  logs"
     echo "     shows logs"
     echo "  cmd <command>"
-    echo "     executes an arbitrary docker compose command. Use \"cmd help\" to list them"
+    echo "     executes an arbitrary Docker Compose command. Use \"cmd help\" to list them"
     echo "  terminate"
     echo "     stops the Optimism node and destroys all data stores"
     echo "  prune-geth"
@@ -612,7 +645,7 @@ printhelp() {
     echo "    shows logs only for op-geth service"
     echo ""
     echo ""
-    echo "$me will attempt to use sudo as needed for docker commands"
+    echo "$me will attempt to use sudo as needed for Docker commands"
     echo ""
 }
 
@@ -674,13 +707,20 @@ fi
 
 check_disk_space
 
-var="COMPOSEV1_NAG"
-value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env" || true)
-
-if [ "${value}" = true ] && [ "${__old_compose}" -eq 1 ]; then
+if [ "${__compose_upgraded}" -eq 1 ]; then
   echo
-  echo "You are using docker-compose ${__compose_version}, which is unsupported by Docker, Inc. from June 2023 on."
-  echo "A switch to docker-ce is recommended. It is *not* mandatory. This is unfortunately a manual step that optimism-docker cannot do for you."
-  echo "Please see https://eth-docker.net/Usage/Prerequisites#switching-from-dockerio-to-docker-ce for instructions."
-  echo "You can turn this message off by adjusting COMPOSEV1_NAG in .env"
+  echo "You updated Docker Compose to V2."
+  echo "The \"docker-compose\" command is gone and replaced with \"docker compose\"."
+  echo "You can create yourself an alias for \"docker-compose\"."
+  echo
+  echo "Optionally, you can switch to docker-ce."
+  echo "Please see https://ethdocker.com/Usage/Prerequisites#switching-from-dockerio-to-docker-ce for instructions."
+elif [ "${__old_compose}" -eq 1 ]; then
+  echo
+  echo "You are using docker-compose ${__compose_version}, which is unsupported by Docker, Inc. since July 2023."
+  echo "${__project_name} will stop supporting it sometime fall 2023."
+  echo ""
+  echo "A switch to docker-ce is recommended. It is *not* mandatory. This is unfortunately a manual step that"
+  echo "${__project_name} cannot do for you."
+  echo "Please see https://ethdocker.com/Usage/Prerequisites#switching-from-dockerio-to-docker-ce for instructions."
 fi
