Snap sync and ethd improved

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -263,32 +263,84 @@ install() {
 }
 
 
-# Warn user if space is low, so they can prune
-check_disk_space() {
+__get_docker_free_space() { # set __free_space to what's available to Docker
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    __free_space=$(dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy | awk '/[0-9]%/{print $(NF-2)}')
+  else
     __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
     __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
+  fi
 
-    re='^[0-9]+$'
-    if ! [[ "${__free_space}" =~ $re ]] ; then
-        echo "Unable to determine free disk space. This is likely a bug."
-        echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-        exit 70
+  re='^[0-9]+$'
+  if ! [[ "${__free_space}" =~ $re ]] ; then
+    echo "Unable to determine free disk space. This is likely a bug."
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+      echo "df reports $(dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy) and __free_space is ${__free_space}"
+    else
+      echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
     fi
+    exit 70
+  fi
+}
 
-    var="COMPOSE_FILE"
-    value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}" || true)
 
-    if [[ "${__free_space}" -lt 52428800 ]]; then
-        echo ""
-        echo "You have less than 50 GiB of free disk space:"
-        echo ""
-        df -h "${__docker_dir}"
-        echo ""
-        echo "Pruning does not appear an option for your client mix."
-        echo "A resync may help."
-        echo "If total space is less than 1.5 TiB, consider cloning to a larger drive."
-        echo ""
-    fi
+__display_docker_dir() {
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    echo "Here's total and used space on Docker's virtual volume"
+    dodocker run --rm -v macos-space-check:/dummy busybox df -h /dummy
+  else
+    echo "Here's total and used space on ${__docker_dir}"
+    df -h "${__docker_dir}"
+  fi
+}
+
+
+__display_docker_volumes() {
+  echo
+  if [ -z "$(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
+    echo "There are no Docker volumes for this copy of ${__project_name}"
+    echo
+  else
+    echo "Here are the Docker volumes used by this copy of ${__project_name} and their space usage:"
+    dodocker system df -v | grep -A 50 "VOLUME NAME" | grep "^$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
+    echo
+    echo "If your Consensus Layer client takes more than 200 GiB, you can resync it with"
+    echo "\"${__me} resync-consensus\"."
+    echo
+  fi
+  echo "If there is some mystery space being taken up, try \"sudo ncdu /\"."
+  echo
+}
+
+
+space() {
+  __get_docker_free_space
+  echo
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    echo "You have $(( __free_space / 1024 / 1024 )) GiB free for Docker volumes"
+  else
+    echo "You have $(( __free_space / 1024 / 1024 )) GiB free on ${__docker_dir}"
+  fi
+  echo
+  __display_docker_dir
+  __display_docker_volumes
+}
+
+
+# Warn user if space is low, so they can prune
+check_disk_space() {
+  __get_docker_free_space
+
+  if [[ "${__free_space}" -lt 52428800 ]]; then
+    echo
+    echo "You have less than 50 GiB of free disk space:"
+    echo
+    __display_docker_dir
+    echo
+    echo "Pruning does not appear an option for your client mix."
+    echo "If total space is less than 1.5 TiB, consider cloning to a larger drive."
+    __display_docker_volumes
+  fi
 }
 
 
@@ -356,16 +408,9 @@ update() {
         exit 1
     fi
 
-    __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
-    __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
-
-    re='^[0-9]+$'
-    if ! [[ "${__free_space}" =~ $re ]] ; then
-        echo "Unable to determine free disk space. This is likely a bug."
-        echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-        exit 70
-    elif [ "${__free_space}" -lt 1048576 ]; then
-        echo "You have less than 1 GiB of space left on ${__docker_dir}."
+    __get_docker_free_space
+    if [ "${__free_space}" -lt 1048576 ]; then
+        echo "You have less than 1 GiB of space left for Docker volumes."
         echo "Aborting, as an update is not safe."
         exit 1
     fi
@@ -428,9 +473,10 @@ envmigrate() {
         return
     fi
 
-    ALL_VARS=( COMPOSE_FILE NETWORK SNAPSHOT L1_RPC L1_RPC_KIND L1_BEACON SEQUENCER LEGACY_TAR LEGACY EL_EXTRAS CL_EXTRAS \
-            LOG_LEVEL OPNODE_DOCKER_TAG OPGETH_DOCKER_TAG L2GETH_DOCKER_TAG DOMAIN RPC_HOST RPC_LB OPNODE_HOST \
-            OPNODE_LB WS_HOST WS_LB RPC_PORT WS_PORT OPNODE_RPC_PORT OPNODE_P2P_PORT L2_CONNECTION_KIND )
+    ALL_VARS=( COMPOSE_FILE NETWORK SNAPSHOT L1_RPC L1_RPC_KIND L1_BEACON SEQUENCER LEGACY_TAR LEGACY EL_EXTRAS \
+            CL_EXTRAS LOG_LEVEL OPNODE_DOCKER_TAG OPGETH_DOCKER_TAG L2GETH_DOCKER_TAG DOMAIN RPC_HOST RPC_LB \
+            OPNODE_HOST OPNODE_LB WS_HOST WS_LB RPC_PORT WS_PORT OPGETH_P2P_PORT OPNODE_RPC_PORT OPNODE_P2P_PORT \
+            L2_CONNECTION_KIND )
     OLD_VARS=( )
     NEW_VARS=( )
 
@@ -605,40 +651,42 @@ version() {
 
 
 help() {
-    echo "usage: ${__me} [-h|--help] <command>"
-    echo
-    echo "commands:"
-    echo "  install"
-    echo "     attempts to install Docker and Docker Compose for you"
-    echo "  update "
-    echo "     updates all client versions and ${__project_name} itself"
-    echo "  up|start"
-    echo "     starts the ${__app_name}, or restarts containers that had their image or"
-    echo "     configuration changed"
-    echo "  down|stop [service-name]"
-    echo "     stops the ${__app_name}, or a specific service by name"
-    echo "  restart [service-name]"
-    echo "     restarts the ${__app_name}, or a specific service by name, a combination of down and up"
-    echo "  version"
-    echo "     prints the version(s) of currently running client(s)"
-    echo "  logs"
-    echo "     shows logs"
-    echo "  cmd <command>"
-    echo "     executes an arbitrary Docker Compose command. Use \"cmd help\" to list them"
-    echo "  terminate"
-    echo "     stops the ${__app_name} and destroys all data stores"
-    echo "  help"
-    echo "      print this help screen"
-    echo
-    echo
-    echo "The logs command can be appended by flags and specify the container(s). example: "
-    echo
-    echo "  $__me logs -f --tail 50 ${__sample_service}"
-    echo "    shows logs only for ${__sample_service} service"
-    echo
-    echo
-    echo "$__me will attempt to use sudo as needed for Docker commands"
-    echo
+  echo "usage: ${__me} [-h|--help] <command>"
+  echo
+  echo "commands:"
+  echo "  install"
+  echo "     attempts to install Docker and Docker Compose for you"
+  echo "  update "
+  echo "     updates all client versions and ${__project_name} itself"
+  echo "  up|start"
+  echo "     starts the ${__app_name}, or restarts containers that had their image or"
+  echo "     configuration changed"
+  echo "  down|stop [service-name]"
+  echo "     stops the ${__app_name}, or a specific service by name"
+  echo "  restart [service-name]"
+  echo "     restarts the ${__app_name}, or a specific service by name, a combination of down and up"
+  echo "  version"
+  echo "     prints the version(s) of currently running client(s)"
+  echo "  logs"
+  echo "     shows logs"
+  echo "  cmd <command>"
+  echo "     executes an arbitrary Docker Compose command. Use \"cmd help\" to list them"
+  echo "  terminate"
+  echo "     stops the ${__app_name} and destroys all data stores"
+  echo "  space"
+  echo "    show Docker volume space usage"
+  echo "  help"
+  echo "      print this help screen"
+  echo
+  echo
+  echo "The logs command can be appended by flags and specify the container(s). example: "
+  echo
+  echo "  $__me logs -f --tail 50 ${__sample_service}"
+  echo "    shows logs only for ${__sample_service} service"
+  echo
+  echo
+  echo "$__me will attempt to use sudo as needed for Docker commands"
+  echo
 }
 
 # Main body from here
@@ -658,13 +706,8 @@ fi
 
 cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
 # Use this to make sure root doesn't end up owning files
-if [[ "$OSTYPE" == "darwin"* ]]; then
-# This is a macOS-ism
-# shellcheck disable=SC2016
-    OWNER=$(stat -f '$Su' .)
-else
-    OWNER=$(stat -c '%U' .)
-fi
+# shellcheck disable=SC2012
+OWNER=$(ls -ld . | awk '{print $3}')
 
 if [ "${OWNER}" == "root" ]; then
     echo "Please install ${__project_name} as a non-root user."
@@ -709,7 +752,7 @@ if ! docompose --help >/dev/null 2>&1; then
 fi
 
 case "$__command" in
-    help|update|up|start|down|stop|restart|version|logs|cmd|terminate)
+    help|update|up|start|down|stop|restart|version|logs|cmd|terminate|space)
         $__command "$@";;
     *)
         echo "Unrecognized command $__command"
